import type { SupportedLocale } from '../../i18n/config';
import type { FAQUIStrings, FAQCategory } from './types';

export const FAQ_UI_TRANSLATIONS: Record<SupportedLocale, FAQUIStrings> = {
  en: {
    badge: '💡 KNOWLEDGE BASE & FAQ',
    defaultTitle: 'Frequently Asked Questions',
    defaultSubtitle: 'Expert answers on touch typing techniques, speed benchmarks, keyboard history, finger placement, and free arcade games.',
    searchPlaceholder: 'Search 37 questions...',
    searchAriaLabel: 'Search frequently asked questions',
    expandAll: 'Expand All',
    collapseAll: 'Collapse All',
    showing: 'Showing',
    of: 'of',
    questions: 'questions',
    categoryLabel: 'Category:',
    allQuestions: 'All Questions',
    related: 'Related:',
    noResultsTitle: 'No matching questions found',
    noResultsDesc: 'Try changing your search query or clicking "All Questions".',
    resetFilters: 'Reset Filters'
  },
  hi: {
    badge: '💡 ज्ञान केंद्र एवं अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    defaultTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    defaultSubtitle: 'टच टाइपिंग तकनीक, स्पीड मानक (WPM), कीबोर्ड इतिहास, उंगलियों की स्थिति और मुफ्त आर्केड गेम्स पर विशेषज्ञ उत्तर।',
    searchPlaceholder: '37 प्रश्नों में खोजें...',
    searchAriaLabel: 'अक्सर पूछे जाने वाले प्रश्न खोजें',
    expandAll: 'सभी खोलें',
    collapseAll: 'सभी बंद करें',
    showing: 'दिखाए जा रहे हैं',
    of: 'में से',
    questions: 'प्रश्न',
    categoryLabel: 'श्रेणी:',
    allQuestions: 'सभी प्रश्न',
    related: 'संबंधित विषय:',
    noResultsTitle: 'कोई मेल खाता प्रश्न नहीं मिला',
    noResultsDesc: 'अपनी खोज क्वेरी बदलें या "सभी प्रश्न" पर क्लिक करें।',
    resetFilters: 'फ़िल्टर रीसेट करें'
  },
  es: {
    badge: '💡 BASE DE CONOCIMIENTO Y PREGUNTAS FRECUENTES',
    defaultTitle: 'Preguntas Frecuentes sobre Mecanografía',
    defaultSubtitle: 'Respuestas de expertos sobre técnicas de mecanografía al tacto, velocidad PPM, historia del teclado y juegos arcade gratis.',
    searchPlaceholder: 'Buscar en 37 preguntas...',
    searchAriaLabel: 'Buscar preguntas frecuentes',
    expandAll: 'Desplegar Todo',
    collapseAll: 'Contraer Todo',
    showing: 'Mostrando',
    of: 'de',
    questions: 'preguntas',
    categoryLabel: 'Categoría:',
    allQuestions: 'Todas las Preguntas',
    related: 'Relacionado:',
    noResultsTitle: 'No se encontraron preguntas coincidentes',
    noResultsDesc: 'Intenta modificar tu búsqueda o haz clic en "Todas las Preguntas".',
    resetFilters: 'Restablecer Filtros'
  },
  fr: {
    badge: '💡 BASE DE CONNAISSANCES & FAQ',
    defaultTitle: 'Foire Aux Questions (FAQ)',
    defaultSubtitle: 'Réponses d’experts sur les techniques de frappe à 10 doigts, les normes MPM, l’histoire des claviers et les jeux arcade gratuits.',
    searchPlaceholder: 'Rechercher parmi 37 questions...',
    searchAriaLabel: 'Rechercher dans les questions fréquentes',
    expandAll: 'Tout Développer',
    collapseAll: 'Tout Réduire',
    showing: 'Affichage de',
    of: 'sur',
    questions: 'questions',
    categoryLabel: 'Catégorie :',
    allQuestions: 'Toutes les Questions',
    related: 'Associé :',
    noResultsTitle: 'Aucune question correspondante trouvée',
    noResultsDesc: 'Essayez de modifier vos termes de recherche ou cliquez sur "Toutes les Questions".',
    resetFilters: 'Réinitialiser les Filtres'
  },
  de: {
    badge: '💡 WISSENSDATENBANK & FAQ',
    defaultTitle: 'Häufig Gestellte Fragen (FAQ)',
    defaultSubtitle: 'Expertenantworten zum Zehnfingersystem, WPM-Benchmarks, Tastatur-Geschichte, Fingerplatzierung und kostenlosen Arcade-Spielen.',
    searchPlaceholder: '37 Fragen durchsuchen...',
    searchAriaLabel: 'Häufig gestellte Fragen durchsuchen',
    expandAll: 'Alle Ausklappen',
    collapseAll: 'Alle Einklappen',
    showing: 'Angezeigt werden',
    of: 'von',
    questions: 'Fragen',
    categoryLabel: 'Kategorie:',
    allQuestions: 'Alle Fragen',
    related: 'Verwandt:',
    noResultsTitle: 'Keine passenden Fragen gefunden',
    noResultsDesc: 'Versuchen Sie einen anderen Suchbegriff oder klicken Sie auf "Alle Fragen".',
    resetFilters: 'Filter Zurücksetzen'
  },
  ja: {
    badge: '💡 ナレッジベース ＆ よくある質問（FAQ）',
    defaultTitle: 'タイピングに関するよくある質問（FAQ）',
    defaultSubtitle: 'タッチタイピングの技術、WPMスピード基準、キーボードの歴史、正しい指の配置、無料アーケードゲームに関する専門家の回答。',
    searchPlaceholder: '37件の質問を検索...',
    searchAriaLabel: 'よくある質問を検索',
    expandAll: 'すべて展開',
    collapseAll: 'すべて折りたたむ',
    showing: '表示中：',
    of: '／全',
    questions: '問',
    categoryLabel: 'カテゴリ：',
    allQuestions: 'すべての質問',
    related: '関連キーワード：',
    noResultsTitle: '一致する質問が見つかりませんでした',
    noResultsDesc: '検索ワードを変更するか、「すべての質問」をクリックしてください。',
    resetFilters: 'フィルターをリセット'
  },
  pt: {
    badge: '💡 BASE DE CONHECIMENTO E PERGUNTAS FREQUENTES',
    defaultTitle: 'Perguntas Frequentes (FAQ)',
    defaultSubtitle: 'Respostas de especialistas sobre técnicas de digitação tátil, referências de PPM/WPM, história do teclado e jogos arcade gratuitos.',
    searchPlaceholder: 'Pesquisar 37 perguntas...',
    searchAriaLabel: 'Pesquisar perguntas frequentes',
    expandAll: 'Expandir Tudo',
    collapseAll: 'Recolher Tudo',
    showing: 'Exibindo',
    of: 'de',
    questions: 'perguntas',
    categoryLabel: 'Categoria:',
    allQuestions: 'Todas as Perguntas',
    related: 'Relacionado:',
    noResultsTitle: 'Nenhuma pergunta correspondente encontrada',
    noResultsDesc: 'Tente alterar os termos da sua pesquisa ou clique em "Todas as Perguntas".',
    resetFilters: 'Redefinir Filtros'
  },
  ru: {
    badge: '💡 БАЗА ЗНАНИЙ И ЧАСТЫЕ ВОПРОСЫ (FAQ)',
    defaultTitle: 'Часто Задаваемые Вопросы (FAQ)',
    defaultSubtitle: 'Ответы экспертов о технике слепой десятипальцевой печати, стандартах WPM/CPM, истории клавиатуры и бесплатных аркадных играх.',
    searchPlaceholder: 'Поиск по 37 вопросам...',
    searchAriaLabel: 'Поиск среди частых вопросов',
    expandAll: 'Развернуть Все',
    collapseAll: 'Свернуть Все',
    showing: 'Показано',
    of: 'из',
    questions: 'вопросов',
    categoryLabel: 'Категория:',
    allQuestions: 'Все Вопросы',
    related: 'Похожие темы:',
    noResultsTitle: 'Совпадающих вопросов не найдено',
    noResultsDesc: 'Попробуйте изменить поисковый запрос или выберите «Все Вопросы».',
    resetFilters: 'Сбросить Фильтры'
  },
  ar: {
    badge: '💡 قاعدة المعرفة والأسئلة الشائعة',
    defaultTitle: 'الأسئلة الشائعة حول سرعة وتقنيات الطباعة',
    defaultSubtitle: 'إجابات شاملة من الخبراء حول تقنيات الطباعة باللمس بعشرة أصابع، معايير السرعة، تاريخ لوحات المفاتيح والألعاب المجانية.',
    searchPlaceholder: 'البحث في 37 سؤالاً...',
    searchAriaLabel: 'البحث في الأسئلة الشائعة',
    expandAll: 'توسيع الكل',
    collapseAll: 'طي الكل',
    showing: 'عرض',
    of: 'من أصل',
    questions: 'سؤالاً',
    categoryLabel: 'التصنيف:',
    allQuestions: 'جميع الأسئلة',
    related: 'مواضيع ذات صلة:',
    noResultsTitle: 'لم يتم العثور على أسئلة مطابقة',
    noResultsDesc: 'يرجى تجربة كلمات بحث أخرى أو النقر على "جميع الأسئلة".',
    resetFilters: 'إعادة ضبط الفلاتر'
  },
  zh: {
    badge: '💡 知识库与常见问题解答（FAQ）',
    defaultTitle: '打字与键盘常见问题解答',
    defaultSubtitle: '关于十指盲打技术、WPM打字速度标准、键盘布局历史、手指键位分工及免费街机打字游戏的权威解答。',
    searchPlaceholder: '搜索全部 37 个问题...',
    searchAriaLabel: '搜索常见问题',
    expandAll: '展开全部',
    collapseAll: '折叠全部',
    showing: '正在显示',
    of: '共',
    questions: '个问题',
    categoryLabel: '分类：',
    allQuestions: '全部问题',
    related: '相关标签：',
    noResultsTitle: '未找到匹配的问题',
    noResultsDesc: '请尝试更换搜索关键词或点击“全部问题”。',
    resetFilters: '重置筛选条件'
  },
  it: {
    badge: '💡 BASE DI CONOSCENZA & DOMANDE FREQUENTI',
    defaultTitle: 'Domande Frequenti sulla Dattilografia',
    defaultSubtitle: 'Risposte di esperti su tecniche di digitazione a 10 dita, standard di velocità WPM, storia delle tastiere e giochi arcade gratuiti.',
    searchPlaceholder: 'Cerca tra 37 domande...',
    searchAriaLabel: 'Cerca tra le domande frequenti',
    expandAll: 'Espandi Tutto',
    collapseAll: 'Comprimi Tutto',
    showing: 'Visualizzazione di',
    of: 'su',
    questions: 'domande',
    categoryLabel: 'Categoria:',
    allQuestions: 'Tutte le Domande',
    related: 'Argomenti correlati:',
    noResultsTitle: 'Nessuna domanda corrispondente trovata',
    noResultsDesc: 'Prova a modificare i termini di ricerca o clicca su "Tutte le Domande".',
    resetFilters: 'Reimposta Filtri'
  },
  ko: {
    badge: '💡 지식 베이스 및 자주 묻는 질문 (FAQ)',
    defaultTitle: '타자 및 키보드 자주 묻는 질문',
    defaultSubtitle: '10손가락 자리익히기(터치 타이핑) 기술, 타자 속도 기준(WPM/타/분), 키보드 역사 및 무료 아케이드 게임에 대한 전문가 답변.',
    searchPlaceholder: '37개 질문 검색...',
    searchAriaLabel: '자주 묻는 질문 검색',
    expandAll: '모두 펼치기',
    collapseAll: '모두 접기',
    showing: '표시 중:',
    of: '/',
    questions: '개 질문',
    categoryLabel: '카테고리:',
    allQuestions: '전체 질문',
    related: '관련 키워드:',
    noResultsTitle: '일치하는 질문이 없습니다',
    noResultsDesc: '검색어를 변경하거나 "전체 질문"을 클릭해 보세요.',
    resetFilters: '필터 초기화'
  },
  id: {
    badge: '💡 PUSAT PENGETAHUAN & FAQ',
    defaultTitle: 'Pertanyaan yang Sering Diajukan (FAQ)',
    defaultSubtitle: 'Jawaban pakar tentang teknik mengetik 10 jari (touch typing), standar kecepatan WPM, sejarah keyboard, dan game arcade gratis.',
    searchPlaceholder: 'Cari 37 pertanyaan...',
    searchAriaLabel: 'Cari pertanyaan yang sering diajukan',
    expandAll: 'Buka Semua',
    collapseAll: 'Tutup Semua',
    showing: 'Menampilkan',
    of: 'dari',
    questions: 'pertanyaan',
    categoryLabel: 'Kategori:',
    allQuestions: 'Semua Pertanyaan',
    related: 'Terkait:',
    noResultsTitle: 'Tidak ada pertanyaan yang cocok',
    noResultsDesc: 'Coba ubah kata kunci pencarian Anda atau klik "Semua Pertanyaan".',
    resetFilters: 'Atur Ulang Filter'
  },
  tr: {
    badge: '💡 BİLGİ MERKEZİ VE SSS',
    defaultTitle: 'Sıkça Sorulan Sorular (SSS)',
    defaultSubtitle: 'On parmak klavye teknikleri, DKS/WPM hız standartları, klavye tarihi, parmak yerleşimi ve ücretsiz atari oyunları hakkında uzman yanıtları.',
    searchPlaceholder: '37 soru içinde ara...',
    searchAriaLabel: 'Sıkça sorulan sorularda ara',
    expandAll: 'Tümünü Genişlet',
    collapseAll: 'Tümünü Daralt',
    showing: 'Gösterilen:',
    of: '/',
    questions: 'soru',
    categoryLabel: 'Kategori:',
    allQuestions: 'Tüm Sorular',
    related: 'İlgili Konular:',
    noResultsTitle: 'Eşleşen soru bulunamadı',
    noResultsDesc: 'Arama ifadenizi değiştirmeyi deneyin veya "Tüm Sorular"a tıklayın.',
    resetFilters: 'Filtreleri Sıfırla'
  },
  vi: {
    badge: '💡 TRUNG TÂM KIẾN THỨC & CÂU HỎI THƯỜNG GẶP',
    defaultTitle: 'Câu Hỏi Thường Gặp (FAQ)',
    defaultSubtitle: 'Giải đáp chuyên sâu về kỹ thuật gõ 10 ngón không nhìn phím, chuẩn tốc độ WPM, lịch sử bàn phím và game arcade gõ phím miễn phí.',
    searchPlaceholder: 'Tìm kiếm trong 37 câu hỏi...',
    searchAriaLabel: 'Tìm kiếm câu hỏi thường gặp',
    expandAll: 'Mở Rộng Tất Cả',
    collapseAll: 'Thu Gọn Tất Cả',
    showing: 'Đang hiển thị',
    of: 'trên tổng số',
    questions: 'câu hỏi',
    categoryLabel: 'Danh mục:',
    allQuestions: 'Tất Cả Câu Hỏi',
    related: 'Liên quan:',
    noResultsTitle: 'Không tìm thấy câu hỏi phù hợp',
    noResultsDesc: 'Hãy thử thay đổi từ khóa tìm kiếm hoặc nhấn vào "Tất Cả Câu Hỏi".',
    resetFilters: 'Đặt Lại Bộ Lọc'
  },
  bn: {
    badge: '💡 জ্ঞান কেন্দ্র ও সাধারণ প্রশ্নোত্তর (FAQ)',
    defaultTitle: 'টাইপিং সম্পর্কিত সাধারণ প্রশ্নোত্তর (FAQ)',
    defaultSubtitle: '১০ আঙুলে না দেখে টাইপিং শেখার কৌশল, WPM গতির মানদণ্ড, কীবোর্ডের ইতিহাস, আঙুলের সঠিক অবস্থান এবং বিনামূল্যে আর্কেড গেম নিয়ে বিশেষজ্ঞদের উত্তর।',
    searchPlaceholder: '৩৭টি প্রশ্নের মধ্যে অনুসন্ধান করুন...',
    searchAriaLabel: 'সাধারণ প্রশ্ন খুঁজুন',
    expandAll: 'সবগুলো খুলুন',
    collapseAll: 'সবগুলো বন্ধ করুন',
    showing: 'প্রদর্শিত হচ্ছে',
    of: 'এর মধ্যে',
    questions: 'টি প্রশ্ন',
    categoryLabel: 'বিভাগ:',
    allQuestions: 'সব প্রশ্ন',
    related: 'সম্পর্কিত বিষয়:',
    noResultsTitle: 'কোনো মিল পাওয়া যায়নি',
    noResultsDesc: 'অনুগ্রহ করে অনুসন্ধানের শব্দ পরিবর্তন করুন অথবা "সব প্রশ্ন" এ ক্লিক করুন।',
    resetFilters: 'ফিল্টার রিসেট করুন'
  }
};

export const FAQ_CATEGORIES_TRANSLATIONS: Record<SupportedLocale, FAQCategory[]> = {
  en: [
    { id: 'all', label: 'All Questions', count: 37, icon: '📋' },
    { id: 'games', label: 'Typing Games & Tools', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Speed & Benchmarks (WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Fingers & Technique', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Keyboards, QWERTY & History', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Practice & Learning', count: 6, icon: '📚' }
  ],
  hi: [
    { id: 'all', label: 'सभी प्रश्न', count: 37, icon: '📋' },
    { id: 'games', label: 'टाइपिंग गेम्स और टूल्स', count: 5, icon: '🎮' },
    { id: 'speed', label: 'स्पीड और मानक (WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'उंगलियां और तकनीक', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'कीबोर्ड, QWERTY और इतिहास', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'अभ्यास और सीखना', count: 6, icon: '📚' }
  ],
  es: [
    { id: 'all', label: 'Todas las Preguntas', count: 37, icon: '📋' },
    { id: 'games', label: 'Juegos y Herramientas', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Velocidad y Métricas (PPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Dedos y Técnica', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Teclados, QWERTY e Historia', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Práctica y Aprendizaje', count: 6, icon: '📚' }
  ],
  fr: [
    { id: 'all', label: 'Toutes les Questions', count: 37, icon: '📋' },
    { id: 'games', label: 'Jeux & Outils de Frappe', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Vitesse & Normes (MPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Doigts & Technique', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Claviers, QWERTY/AZERTY & Histoire', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Entraînement & Apprentissage', count: 6, icon: '📚' }
  ],
  de: [
    { id: 'all', label: 'Alle Fragen', count: 37, icon: '📋' },
    { id: 'games', label: 'Tippspiele & Werkzeuge', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Geschwindigkeit & WPM', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Finger & Technik', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Tastaturen, QWERTY & Geschichte', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Übung & Lernen', count: 6, icon: '📚' }
  ],
  ja: [
    { id: 'all', label: 'すべての質問', count: 37, icon: '📋' },
    { id: 'games', label: 'タイピングゲーム・ツール', count: 5, icon: '🎮' },
    { id: 'speed', label: '速度基準・WPM', count: 9, icon: '⚡' },
    { id: 'technique', label: '指の配置・テクニック', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'キーボード・配列・歴史', count: 8, icon: '⌨️' },
    { id: 'practice', label: '練習・学習方法', count: 6, icon: '📚' }
  ],
  pt: [
    { id: 'all', label: 'Todas as Perguntas', count: 37, icon: '📋' },
    { id: 'games', label: 'Jogos e Ferramentas', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Velocidade e Métricas (PPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Dedos e Técnica', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Teclados, QWERTY e História', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Prática e Aprendizado', count: 6, icon: '📚' }
  ],
  ru: [
    { id: 'all', label: 'Все Вопросы', count: 37, icon: '📋' },
    { id: 'games', label: 'Тренажеры и Игры', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Скорость и Нормативы (WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Пальцы и Техника Печати', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Клавиатуры, QWERTY и История', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Обучение и Практика', count: 6, icon: '📚' }
  ],
  ar: [
    { id: 'all', label: 'جميع الأسئلة', count: 37, icon: '📋' },
    { id: 'games', label: 'ألعاب الطباعة والأدوات', count: 5, icon: '🎮' },
    { id: 'speed', label: 'السرعة ومعايير ك/د (WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'وضعيات الأصابع والتقنية', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'لوحات المفاتيح وتاريخ QWERTY', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'التدريب والتعلم', count: 6, icon: '📚' }
  ],
  zh: [
    { id: 'all', label: '全部问题', count: 37, icon: '📋' },
    { id: 'games', label: '打字游戏与测试工具', count: 5, icon: '🎮' },
    { id: 'speed', label: '打字速度与评级 (WPM/CPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: '手指分工与盲打技巧', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: '键盘架构、QWERTY历史', count: 8, icon: '⌨️' },
    { id: 'practice', label: '日常练习与技巧提升', count: 6, icon: '📚' }
  ],
  it: [
    { id: 'all', label: 'Tutte le Domande', count: 37, icon: '📋' },
    { id: 'games', label: 'Giochi di Dattilografia', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Velocità e Standard (PPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Dita e Tecnica di Digitazione', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Tastiere, QWERTY e Storia', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Esercizi e Apprendimento', count: 6, icon: '📚' }
  ],
  ko: [
    { id: 'all', label: '전체 질문', count: 37, icon: '📋' },
    { id: 'games', label: '타자 게임 및 도구', count: 5, icon: '🎮' },
    { id: 'speed', label: '타자 속도 및 기준 (WPM/타)', count: 9, icon: '⚡' },
    { id: 'technique', label: '손가락 위치 및 타법', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: '키보드, QWERTY 및 역사', count: 8, icon: '⌨️' },
    { id: 'practice', label: '연습 및 학습법', count: 6, icon: '📚' }
  ],
  id: [
    { id: 'all', label: 'Semua Pertanyaan', count: 37, icon: '📋' },
    { id: 'games', label: 'Game Mengetik & Alat', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Kecepatan & Standar WPM', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Jari & Teknik Mengetik', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Keyboard, QWERTY & Sejarah', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Latihan & Pembelajaran', count: 6, icon: '📚' }
  ],
  tr: [
    { id: 'all', label: 'Tüm Sorular', count: 37, icon: '📋' },
    { id: 'games', label: 'Yazma Oyunları ve Araçlar', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Hız ve Standartlar (DKS/WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Parmaklar ve Teknik', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Klavyeler, QWERTY ve Tarih', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Pratik ve Öğrenme', count: 6, icon: '📚' }
  ],
  vi: [
    { id: 'all', label: 'Tất Cả Câu Hỏi', count: 37, icon: '📋' },
    { id: 'games', label: 'Game & Công Cụ Gõ Phím', count: 5, icon: '🎮' },
    { id: 'speed', label: 'Tốc Độ & Tiêu Chuẩn WPM', count: 9, icon: '⚡' },
    { id: 'technique', label: 'Ngón Tay & Kỹ Thuật Gõ', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'Bàn Phím, QWERTY & Lịch Sử', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'Luyện Tập & Học Tập', count: 6, icon: '📚' }
  ],
  bn: [
    { id: 'all', label: 'সব প্রশ্ন', count: 37, icon: '📋' },
    { id: 'games', label: 'টাইপিং গেম ও টুলস', count: 5, icon: '🎮' },
    { id: 'speed', label: 'গতি ও মানদণ্ড (WPM)', count: 9, icon: '⚡' },
    { id: 'technique', label: 'আঙুল ও টাইপিং কৌশল', count: 9, icon: '🖐️' },
    { id: 'keyboards', label: 'কীবোর্ড, QWERTY ও ইতিহাস', count: 8, icon: '⌨️' },
    { id: 'practice', label: 'অনুশীলন ও শেখা', count: 6, icon: '📚' }
  ]
};

export function getLocalizedFAQUI(locale: string = 'en'): FAQUIStrings {
  const norm = (locale || 'en').toLowerCase().trim() as SupportedLocale;
  return FAQ_UI_TRANSLATIONS[norm] || FAQ_UI_TRANSLATIONS.en;
}

export function getLocalizedFAQCategories(locale: string = 'en'): FAQCategory[] {
  const norm = (locale || 'en').toLowerCase().trim() as SupportedLocale;
  return FAQ_CATEGORIES_TRANSLATIONS[norm] || FAQ_CATEGORIES_TRANSLATIONS.en;
}
